export const MOCK_KEYWORDS = [
  { keyword: "seo audit checklist", searchVolume: 12400, difficulty: 32, competitorRank: "#3", opportunityScore: 91 },
  { keyword: "schema markup guide", searchVolume: 8900, difficulty: 25, competitorRank: "#2", opportunityScore: 88 },
  { keyword: "local seo tips", searchVolume: 24500, difficulty: 45, competitorRank: "#5", opportunityScore: 79 },
  { keyword: "technical seo guide", searchVolume: 9800, difficulty: 37, competitorRank: "#4", opportunityScore: 85 },
  { keyword: "link building strategies", searchVolume: 18600, difficulty: 62, competitorRank: "#7", opportunityScore: 68 },
  { keyword: "on page seo checklist", searchVolume: 6700, difficulty: 28, competitorRank: "#3", opportunityScore: 87 },
  { keyword: "content gap analysis", searchVolume: 3400, difficulty: 22, competitorRank: "#4", opportunityScore: 90 },
  { keyword: "google search console guide", searchVolume: 19000, difficulty: 41, competitorRank: "#6", opportunityScore: 74 },
  { keyword: "backlink analysis tool", searchVolume: 8100, difficulty: 55, competitorRank: "#9", opportunityScore: 65 },
  { keyword: "site speed optimization", searchVolume: 14300, difficulty: 38, competitorRank: "#5", opportunityScore: 76 },
  { keyword: "core web vitals guide", searchVolume: 11200, difficulty: 35, competitorRank: "#4", opportunityScore: 80 },
  { keyword: "meta description tips", searchVolume: 5600, difficulty: 20, competitorRank: "#2", opportunityScore: 92 },
  { keyword: "image seo optimization", searchVolume: 7800, difficulty: 29, competitorRank: "#5", opportunityScore: 81 },
  { keyword: "mobile seo best practices", searchVolume: 9300, difficulty: 33, competitorRank: "#6", opportunityScore: 77 },
  { keyword: "seo competitor analysis", searchVolume: 6200, difficulty: 42, competitorRank: "#7", opportunityScore: 73 },
  { keyword: "xml sitemap guide", searchVolume: 4500, difficulty: 18, competitorRank: "#3", opportunityScore: 89 },
  { keyword: "robots txt guide", searchVolume: 3900, difficulty: 15, competitorRank: "#2", opportunityScore: 93 },
  { keyword: "canonical tags seo", searchVolume: 3100, difficulty: 21, competitorRank: "#4", opportunityScore: 86 },
  { keyword: "structured data markup", searchVolume: 5500, difficulty: 30, competitorRank: "#5", opportunityScore: 82 },
  { keyword: "seo for beginners guide", searchVolume: 28000, difficulty: 52, competitorRank: "#9", opportunityScore: 67 },
  { keyword: "white hat seo techniques", searchVolume: 7200, difficulty: 37, competitorRank: "#6", opportunityScore: 75 },
  { keyword: "content marketing seo", searchVolume: 16800, difficulty: 48, competitorRank: "#8", opportunityScore: 69 },
  { keyword: "anchor text optimization", searchVolume: 2800, difficulty: 19, competitorRank: "#3", opportunityScore: 90 },
  { keyword: "url structure seo", searchVolume: 4100, difficulty: 23, competitorRank: "#4", opportunityScore: 84 },
  { keyword: "page speed seo impact", searchVolume: 6900, difficulty: 31, competitorRank: "#5", opportunityScore: 79 },
  { keyword: "internal linking strategy", searchVolume: 5800, difficulty: 26, competitorRank: "#3", opportunityScore: 87 },
  { keyword: "featured snippet optimization", searchVolume: 4700, difficulty: 34, competitorRank: "#6", opportunityScore: 76 },
  { keyword: "voice search seo guide", searchVolume: 11600, difficulty: 44, competitorRank: "#7", opportunityScore: 71 },
  { keyword: "eat seo guidelines", searchVolume: 3600, difficulty: 28, competitorRank: "#4", opportunityScore: 83 },
  { keyword: "seo reporting template", searchVolume: 4300, difficulty: 17, competitorRank: "#2", opportunityScore: 94 },
  { keyword: "google algorithm updates", searchVolume: 22000, difficulty: 55, competitorRank: "#10", opportunityScore: 62 },
  { keyword: "seo tools comparison", searchVolume: 9400, difficulty: 43, competitorRank: "#8", opportunityScore: 70 },
  { keyword: "long tail keyword strategy", searchVolume: 7100, difficulty: 30, competitorRank: "#5", opportunityScore: 80 },
  { keyword: "local business seo tips", searchVolume: 18900, difficulty: 47, competitorRank: "#9", opportunityScore: 66 },
  { keyword: "search intent optimization", searchVolume: 5200, difficulty: 32, competitorRank: "#5", opportunityScore: 81 },
  { keyword: "competitor keyword analysis", searchVolume: 4800, difficulty: 35, competitorRank: "#6", opportunityScore: 78 },
  { keyword: "seo content strategy", searchVolume: 8700, difficulty: 40, competitorRank: "#7", opportunityScore: 73 },
  { keyword: "topic cluster strategy", searchVolume: 3300, difficulty: 22, competitorRank: "#3", opportunityScore: 89 },
  { keyword: "domain authority guide", searchVolume: 12100, difficulty: 46, competitorRank: "#8", opportunityScore: 69 },
  { keyword: "page authority seo", searchVolume: 5900, difficulty: 38, competitorRank: "#7", opportunityScore: 74 },
  { keyword: "seo rank tracking", searchVolume: 6500, difficulty: 40, competitorRank: "#6", opportunityScore: 76 },
  { keyword: "google my business seo", searchVolume: 21000, difficulty: 49, competitorRank: "#9", opportunityScore: 65 },
  { keyword: "seo case study examples", searchVolume: 4200, difficulty: 24, competitorRank: "#4", opportunityScore: 85 },
  { keyword: "site audit checklist", searchVolume: 3700, difficulty: 20, competitorRank: "#3", opportunityScore: 90 },
  { keyword: "hreflang implementation", searchVolume: 2900, difficulty: 27, competitorRank: "#5", opportunityScore: 82 },
  { keyword: "crawl budget optimization", searchVolume: 2100, difficulty: 16, competitorRank: "#2", opportunityScore: 95 },
  { keyword: "seo for ecommerce", searchVolume: 14700, difficulty: 51, competitorRank: "#10", opportunityScore: 63 },
  { keyword: "seo kpi metrics", searchVolume: 3500, difficulty: 19, competitorRank: "#3", opportunityScore: 91 },
  { keyword: "javascript seo guide", searchVolume: 4100, difficulty: 33, competitorRank: "#5", opportunityScore: 79 },
  { keyword: "seo audit tools free", searchVolume: 9600, difficulty: 44, competitorRank: "#7", opportunityScore: 70 },
];

export const MOCK_CONTENT_GAPS = [
  { topic: "Technical SEO Fundamentals", competitorCoverage: 95, yourCoverage: 35, opportunityScore: 92, priority: "High" },
  { topic: "Schema Markup Implementation", competitorCoverage: 90, yourCoverage: 20, opportunityScore: 95, priority: "High" },
  { topic: "Local SEO Optimization", competitorCoverage: 80, yourCoverage: 50, opportunityScore: 70, priority: "Medium" },
  { topic: "Core Web Vitals", competitorCoverage: 88, yourCoverage: 40, opportunityScore: 82, priority: "High" },
  { topic: "E-commerce SEO Strategy", competitorCoverage: 75, yourCoverage: 30, opportunityScore: 78, priority: "High" },
  { topic: "Content Strategy & SEO", competitorCoverage: 92, yourCoverage: 60, opportunityScore: 68, priority: "Medium" },
  { topic: "Link Building Tactics", competitorCoverage: 85, yourCoverage: 45, opportunityScore: 74, priority: "Medium" },
  { topic: "Voice Search Optimization", competitorCoverage: 70, yourCoverage: 15, opportunityScore: 85, priority: "High" },
  { topic: "Mobile-First Indexing", competitorCoverage: 82, yourCoverage: 55, opportunityScore: 63, priority: "Medium" },
  { topic: "Featured Snippets Strategy", competitorCoverage: 78, yourCoverage: 25, opportunityScore: 80, priority: "High" },
  { topic: "International SEO", competitorCoverage: 65, yourCoverage: 10, opportunityScore: 88, priority: "High" },
  { topic: "Video SEO Optimization", competitorCoverage: 72, yourCoverage: 30, opportunityScore: 72, priority: "Medium" },
  { topic: "SEO for SaaS Products", competitorCoverage: 80, yourCoverage: 35, opportunityScore: 78, priority: "High" },
  { topic: "Keyword Research Methods", competitorCoverage: 95, yourCoverage: 70, opportunityScore: 55, priority: "Low" },
  { topic: "Competitor Backlink Analysis", competitorCoverage: 88, yourCoverage: 40, opportunityScore: 78, priority: "Medium" },
  { topic: "Content Audit Process", competitorCoverage: 75, yourCoverage: 20, opportunityScore: 84, priority: "High" },
  { topic: "On-Page SEO Checklist", competitorCoverage: 90, yourCoverage: 65, opportunityScore: 58, priority: "Low" },
  { topic: "Google Analytics 4 Setup", competitorCoverage: 85, yourCoverage: 75, opportunityScore: 42, priority: "Low" },
  { topic: "Crawl Error Resolution", competitorCoverage: 82, yourCoverage: 30, opportunityScore: 80, priority: "High" },
  { topic: "SEO Reporting & Dashboards", competitorCoverage: 70, yourCoverage: 25, opportunityScore: 76, priority: "Medium" },
];

export const MOCK_TOPIC_CLUSTERS = [
  { name: "Technical SEO", color: "#3b82f6", subTopics: ["Core Web Vitals", "Site Speed", "Crawl Budget", "Mobile Indexing"] },
  { name: "Link Building", color: "#10b981", subTopics: ["Guest Posting", "Digital PR", "Broken Link Building"] },
  { name: "Local SEO", color: "#f59e0b", subTopics: ["Google Business", "Local Citations", "NAP Consistency"] },
  { name: "On-Page SEO", color: "#8b5cf6", subTopics: ["Title Tags", "Meta Descriptions", "Content Optimization", "Internal Links"] },
  { name: "Keyword Research", color: "#ec4899", subTopics: ["Long Tail Keywords", "Search Intent", "Competitor Analysis"] },
  { name: "Content Marketing", color: "#06b6d4", subTopics: ["Blog Posts", "Infographics", "Video SEO"] },
];

export const MOCK_RECOMMENDATIONS = [
  {
    title: "Create a Technical SEO Guide",
    description: "Your competitor ranks #2 for 12 technical SEO keywords. A comprehensive guide could capture 15K monthly visits.",
    priority: "High",
    impact: "+15k visits/mo",
    effort: "Medium",
    keywords: 12,
  },
  {
    title: "Publish Schema Markup Tutorials",
    description: "Schema markup content has a 95% opportunity score. Competitor dominates with 8 articles on this topic.",
    priority: "High",
    impact: "+8k visits/mo",
    effort: "Low",
    keywords: 8,
  },
  {
    title: "Expand Local SEO Content",
    description: "Local SEO queries show 70% competitor coverage gap. Target location-specific long-tail keywords.",
    priority: "Medium",
    impact: "+12k visits/mo",
    effort: "High",
    keywords: 23,
  },
  {
    title: "Add Internal Linking Articles",
    description: "Internal linking strategy content is missing from your site but drives significant traffic for competitor.",
    priority: "Low",
    impact: "+3k visits/mo",
    effort: "Low",
    keywords: 6,
  },
  {
    title: "Create SEO Audit Templates",
    description: "Template-based content drives high intent traffic. Competitor has 5 downloadable resources in this category.",
    priority: "Medium",
    impact: "+5k visits/mo",
    effort: "Low",
    keywords: 9,
  },
];

export const HEATMAP_DATA = [
  { topic: "Technical SEO", score: 92, level: "High" },
  { topic: "Schema Markup", score: 95, level: "High" },
  { topic: "Local SEO", score: 70, level: "Medium" },
  { topic: "Core Web Vitals", score: 82, level: "High" },
  { topic: "Voice Search", score: 85, level: "High" },
  { topic: "Featured Snippets", score: 80, level: "High" },
  { topic: "International SEO", score: 88, level: "High" },
  { topic: "Link Building", score: 74, level: "Medium" },
  { topic: "Mobile SEO", score: 63, level: "Medium" },
  { topic: "Video SEO", score: 72, level: "Medium" },
  { topic: "Content Audit", score: 84, level: "High" },
  { topic: "E-commerce SEO", score: 78, level: "Medium" },
  { topic: "SaaS SEO", score: 78, level: "Medium" },
  { topic: "Keyword Research", score: 55, level: "Low" },
  { topic: "Backlink Analysis", score: 78, level: "Medium" },
  { topic: "On-Page SEO", score: 58, level: "Low" },
  { topic: "GA4 Setup", score: 42, level: "Low" },
  { topic: "Crawl Errors", score: 80, level: "High" },
  { topic: "SEO Reporting", score: 76, level: "Medium" },
  { topic: "Internal Linking", score: 87, level: "High" },
  { topic: "Site Speed", score: 76, level: "Medium" },
  { topic: "Topic Clusters", score: 89, level: "High" },
  { topic: "Domain Authority", score: 69, level: "Medium" },
  { topic: "Page Authority", score: 74, level: "Medium" },
  { topic: "Rank Tracking", score: 76, level: "Medium" },
  { topic: "Google My Biz", score: 65, level: "Medium" },
  { topic: "URL Structure", score: 84, level: "High" },
  { topic: "Robots.txt", score: 93, level: "High" },
  { topic: "Canonical Tags", score: 86, level: "High" },
  { topic: "Hreflang", score: 82, level: "High" },
];

export const COMPARISON_DATA = [
  { category: "Articles", yourSite: 45, competitor: 87 },
  { category: "Keywords", yourSite: 210, competitor: 620 },
  { category: "Backlinks", yourSite: 1240, competitor: 4800 },
  { category: "Domain Score", yourSite: 38, competitor: 67 },
];
